import React, { useState } from "react";

const Section7 = () => {
  const [activeQuestion, setActiveQuestion] = useState(null);

  const faqs = [
    {
      question: "Is the content unique?",
      answer:
        "95% of the content generated by the AI is unique and original. We also provide a uniqueness score for longer form content generated so you can have peace of mind to know that the content you have received is unique.",
    },
    {
      question: "How is the content generated?",
      answer:
        " We make use of a variety of AI models, with Generative Pre-trained Transformer 3 is an autoregressive language model which uses deep learning to produce human-like text. It's a game changer for content creators.",
    },
    {
      question: "Who retains the copyright?",
      answer:
        "You do. We will not claim copyright over content generated by the AI for you.",
    },
    {
      question: "What languages do you support?",
      answer:
        "We currently support all languages supported by Google Translate.",
    },
    {
      question: "Is there discount for non-profits?",
      answer: "Please get in touch with us below.",
    },
  ];

  const toggleAnswer = (index) => {
    setActiveQuestion(activeQuestion === index ? null : index);
  };

  return (
    <div>
      <section className="relative text-white flex flex-col justify-center items-start mt-20">
        <div className="flex flex-col items-start lg:mx-20 mx-5 md:mx-20">
          <h2 className="lg:text-7xl md:text-5xl text-3xl  font-semibold text-left mt-5">
            <span className="bg-gradient-to-r from-purple-500 to-pink-500 text-transparent bg-clip-text uppercase lg:ml-10 md:ml-10 ml-5 ">
              questions
            </span>
          </h2>
          <h2
            className="lg:text-7xl md:text-5xl text-3xl font-semibold absolute text-center opacity-50 uppercase"
            style={{
              color: "transparent",
              WebkitTextStroke: "2px white",
            }}
          >
            frequently asked
          </h2>
        </div>
        <p className="lg:text-2xl text-lg   mx-[10%] my-[5%] mt-12 lg:mx-30  md:mx-50 mx-42 text-center ">
          We're dedicated to assisting individuals interested in generating
          AI-driven content and images.
        </p>

        <div className="lg:mx-28 md:mx-20 mx-2 lg:w-4/5 md:w-3/4 w-[96%] text-left">
          {faqs.map((faq, index) => (
            <div key={index} className="my-2 bg-[#1B1236]">
              <div
                className="cursor-pointer flex justify-between items-center py-2 px-4 bg-[#1B1236] hover:bg-[#423364] rounded-lg m-0"
                onClick={() => toggleAnswer(index)}
              >
                <h3 className="text-xl font-semibold">{faq.question}</h3>
                <div className="text-2xl">
                  {activeQuestion === index ? "-" : "+"}
                </div>
              </div>
              {index > 0 && <hr className="border-t-2  border-[#221A3D]" />}{" "}
              {activeQuestion === index && (
                <p className="mt-2 text-lg ml-2 bg-[#1B1236] text-left px-4 py-8">
                  {faq.answer}
                </p>
              )}
            </div>
          ))}
        </div>
      </section>
    </div>
  );
};

export default Section7;
